### ISSUE TITLE
Getting Error While Processing

### ISSUE THREAD

**Issue by RFedz007989** [pg56714/Inpaint-Anything-Gradio#1]
Hi,

Hope you are doing good.
I am getting this error while processing & even I am not able to add mask.
Error is (NoneType' object has no attribute 'shape)

Pls have a look & assist me where I am going/doing wrong.
Have a Gr8 Day

Thank You

**Comment by pg56714** [comment]
@RFedz007989 What actions did you perform when you encountered this issue? Please explain your process. Thank you. It's working fine on my end.

Here is the workflow:

1. Upload an image, click on the image in "Upload and Edit Image," select the target you want to process into a mask, and click "Editing Complete" to review the result. Finally, press "Inpaint Image."

2. Upload an image, click on "Upload and Edit Image," select the target you want to process into a mask, enter the text prompt, and use "Fill or Replace Anything."

**Comment by pg56714** [comment]
This issue has remained without a response for over a month, so I will proceed to close it for now.
